/* Generated by scripts/generate-service-worker.mjs. Do not edit by hand. */
/* global caches, fetch, Request, self */
const CACHE_PREFIX = 'vj-tam-tam-app-'
const CACHE_NAME = CACHE_PREFIX + 'c915c4e8aca8b458'
const PRECACHE_URLS = [
  './',
  './assets/css/features/advanced-controls.css',
  './assets/css/features/base.css',
  './assets/css/features/bottom-live-strip.css',
  './assets/css/features/drawer.css',
  './assets/css/features/media-pool.css',
  './assets/css/features/notifications.css',
  './assets/css/features/projection-controls.css',
  './assets/css/features/projection-handles.css',
  './assets/css/features/stage-and-overlays.css',
  './assets/css/features/text-pool.css',
  './assets/css/style.css',
  './assets/img/app-icon-192.png',
  './assets/img/app-icon-512.png',
  './assets/img/app-icon.svg',
  './assets/img/test-card.png',
  './index.html',
  './lib/maptastic.js',
  './manifest.webmanifest',
  './src/colorCorrectionManager.js',
  './src/constants/events.js',
  './src/constants/mediaTypes.js',
  './src/constants/playbackConfig.js',
  './src/constants/stageLayouts.js',
  './src/constants/strings.js',
  './src/defaultState.js',
  './src/eventBus.js',
  './src/facades/fileSystemAccessFacade.js',
  './src/facades/fileSystemFacade.js',
  './src/facades/storageFacade.js',
  './src/idleController.js',
  './src/main.js',
  './src/mediaAccessState.js',
  './src/mediaProcessor.js',
  './src/playbackEngine.js',
  './src/presentationFullscreen.js',
  './src/projectionManager.js',
  './src/stateManager.js',
  './src/testCardManager.js',
  './src/textDisplayManager.js',
  './src/textPoolView.js',
  './src/toastManager.js',
  './src/uiManager.js',
  './src/utils/arrayUtils.js',
  './src/utils/mediaUtils.js',
  './src/utils/objectUtils.js',
  './src/utils/stringUtils.js',
  './src/utils/validationUtils.js',
]

function cacheRequestFor(url) {
  return new Request(new URL(url, self.registration.scope), { cache: 'reload' })
}

function isAppShellRequest(request) {
  if (request.method !== 'GET') return false

  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return false
  if (!url.href.startsWith(self.registration.scope)) return false

  return url.protocol === 'http:' || url.protocol === 'https:'
}

async function networkFirst(request) {
  const cache = await caches.open(CACHE_NAME)

  try {
    const response = await fetch(request)
    if (response?.ok) {
      await cache.put(request, response.clone())
    }
    return response
  } catch (error) {
    const cachedResponse = await cache.match(request)
    if (cachedResponse) {
      return cachedResponse
    }

    if (request.mode === 'navigate') {
      return cache.match(new URL('./index.html', self.registration.scope))
    }

    throw error
  }
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_URLS.map(cacheRequestFor)))
      .then(() => self.skipWaiting())
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((cacheNames) =>
        Promise.all(
          cacheNames
            .filter((cacheName) => cacheName.startsWith(CACHE_PREFIX) && cacheName !== CACHE_NAME)
            .map((cacheName) => caches.delete(cacheName))
        )
      )
      .then(() => self.clients.claim())
  )
})

self.addEventListener('fetch', (event) => {
  if (!isAppShellRequest(event.request)) {
    return
  }

  event.respondWith(networkFirst(event.request))
})
